### ISSUE TITLE
Migrate ENS Subgraph

### ISSUE THREAD

**Issue by Gudduomm** [subsquid-quests/ens-subgraph-migration#11]
This quest is to migrate the ENS Subgraph to Squid SDK. The repo for the subgraph can be found here. The resulting squid should match the GraphQL API of the subgraph as close as possible, by migrating schema.graphql. The judges reserve the right to request improvements afther the initial review of the submission. Reach out to the Discord Channel for any tech questions regarding this quest.

Quest Info
Category	Skill Level	Time required (hours)	Max Participants	Reward	Status
Squid Deployment	
~40	5	
open
Acceptance critera
Each quest should be submitted as a PR and will be reviewed manually. The PR should contain README.MD with

Insturctions how to run the squid locally
Sample Squid queries and the corresponding Subgraph queries
The code should be well documented. The judges will access:

In-line commends where necessary
Clarity of the code
Performance and optimization (if batching and Multicall queries are used whenever appropriate)
Useful links
https://docs.subsquid.io/deploy-squid/quickstart/
TheGraph Migration guide

**Comment by Marin06** [comment]
Nn
