### ISSUE TITLE
Migrate the ENS Subgraph to Squid by Kadua Nganu.

### ISSUE THREAD

**Issue by kaduanganu** [subsquid-quests/ens-subgraph-migration#23]
https://github.com/kaduanganu/ens-subgraph-squid

@abernatskiy @dzhelezov @dariaag @belopash

**Comment by belopash** [comment]
Sorry, but isn't it just the original subgraph? Did you forget to publish submodules?

**Comment by kaduanganu** [comment]
Sorry about that, still not quite familiar with this. I think this is the correct one.

https://github.com/kaduanganu/ens-subgraph-squid/tree/master/kadua-squid-evm

**Comment by kaduanganu** [comment]
> Sorry, but isn't it just the original subgraph? Did you forget to publish submodules?

Sorry about that, still not quite familiar with this. I believe this is the correct one.

https://github.com/kaduanganu/ens-subgraph-squid/tree/master/kadua-squid-evm

@abernatskiy @dzhelezov @dariaag @belopash

**Comment by dariaag** [comment]
this is the gravatar template

**Comment by kaduanganu** [comment]
> this is the gravatar template

Ok, please bear with me. I hope I'm at least getting closer.

Modify README.md
Modify abi/Gravity.json
Modify src/processor.ts

https://github.com/kaduanganu/ens-subgraph-squid/tree/master/kadua-squid-evm

@abernatskiy @dzhelezov @dariaag @belopash

**Comment by dariaag** [comment]
this is the provided template and is indexing the wrong contract
