### ISSUE TITLE
migrate the ENS Subgraph to Squid SDK

### ISSUE THREAD

**Issue by farhanreizha** [subsquid-quests/ens-subgraph-migration#24]
https://github.com/farhanreizha/gravatar-squid-migration

[@dariaag](https://github.com/dariaag), [@belopash](https://github.com/belopash), [@abernatskiy](https://github.com/abernatskiy) and [@dzhelezov](https://github.com/dzhelezov)

**Comment by belopash** [comment]
Task was to migrate ens-subgraph, but not gravatar-subgraph
