### ISSUE TITLE
Migrate ENS Subgraph

### ISSUE THREAD

**Issue by zulmif1** [subsquid-quests/ens-subgraph-migration#30]
Hi everyone, I've completed the task and would appreciate your feedback. You can review it on GitHub: https://github.com/zulmif1/gnb.git

Your input is valuable. Thank you!

@dariaag  @belopash  @abernatskiy  @dzhelezov

**Comment by zulmif1** [comment]
please wait, i will push my README for intro and sample  query

**Comment by belopash** [comment]
not the ens-squid

**Comment by Abi1215** [comment]
tes

**Comment by zulmif1** [comment]
yes sir?
