### ISSUE TITLE
ENS Migration

### ISSUE THREAD

**Issue by akhiljaat9958** [subsquid-quests/ens-subgraph-migration#37]
https://github.com/akhiljaat9958/ENS-Migration
[https://github.com/akhiljaat9958/ENS-Migration](https://github.com/akhiljaat9958/ENS-Migration/issues/url)
@dariaag
@belopash

**Comment by belopash** [comment]
Just a gravatar-squid from tutorial, not ens-subgraph migration

**Comment by akhiljaat9958** [comment]
didn't Understand
